### ISSUE TITLE
Error generating validator code

### ISSUE THREAD

**Issue by nstogner** [GoogleCloudPlatform/magic-modules#1488]
Branch: `master`

Steps to reproduce:

```sh
git clone git@github.com:GoogleCloudPlatform/magic-modules.git
cd magic-modules
./tools/bootstrap
./tools/doctor # Checks out

bundle exec compiler --product products/compute/ --type Instance -e terraform -f validator -o "$GOPATH/src/github.com/GoogleCloudPlatform/terraform-google-conversion"
```

Output:

```
...
bundler: failed to load command: compiler (compiler)
NoMethodError: undefined method `min_version' for nil:NilClass
  /Users/stogner/work/magic-modules/api/type.rb:180:in `min_version'
  /Users/stogner/work/magic-modules/api/type.rb:187:in `exclude_if_not_in_version!'
  /Users/stogner/work/magic-modules/api/type.rb:589:in `exclude_if_not_in_version!'
  /Users/stogner/work/magic-modules/api/type.rb:385:in `exclude_if_not_in_version!'
  /Users/stogner/work/magic-modules/api/resource.rb:231:in `block in exclude_if_not_in_version!'
  /Users/stogner/work/magic-modules/api/resource.rb:231:in `each'
  /Users/stogner/work/magic-modules/api/resource.rb:231:in `exclude_if_not_in_version!'
  /Users/stogner/work/magic-modules/provider/core.rb:192:in `block in generate_objects'
  /Users/stogner/work/magic-modules/provider/core.rb:181:in `each'
  /Users/stogner/work/magic-modules/provider/core.rb:181:in `generate_objects'
  /Users/stogner/work/magic-modules/provider/terraform_object_library.rb:21:in `generate'
  compiler:150:in `block in <top (required)>'
  compiler:102:in `each'
  compiler:102:in `<top (required)>'
```

**Comment by nstogner** [comment]
Found issue: `products/compute/terraform.yaml` needs `exclude: false` to be set for `Instance` in order to use the `third_party/` override file.
