### ISSUE TITLE
TypeError: no implicit conversion of Hash into Integer

### ISSUE THREAD

**Issue by mxplusb** [GoogleCloudPlatform/magic-modules#1724]
**GIVEN**

I am a first time contributor.

**WHEN**

I clone the repo and take these steps:

1. `./tools/bootstrap`
1.`bundle install --path vendor/bundle`
1. `./tools/doctor` <- all good
1. `bundle exec compiler -a -v "ga" -e terraform -o "$GOPATH/src/github.com/terraform-providers/terraform-provider-google"`

**THEN**

I get these errors: 

```
bundle exec compiler -a -v "ga" -e terraform -o "$GOPATH/src/github.com/terraform-providers/terraform-provider-google"
I, [2019-05-06T21:29:58.805219 #62567]  INFO -- : Compiling 'products/resourcemanager' (at ga) output to '/Users/KevinMLloyd/Development/go/src/github.com/terraform-providers/terraform-provider-google'
I, [2019-05-06T21:29:58.805440 #62567]  INFO -- : Generating types: ALL
bundler: failed to load command: compiler (compiler)
TypeError: no implicit conversion of Hash into Integer
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:860:in `block in result'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:862:in `result'
  /Users/kevinmlloyd/Development/tooling/google/magic-modules/compile/core.rb:148:in `compile'
  /Users/kevinmlloyd/Development/tooling/google/magic-modules/provider/config.rb:51:in `parse'
  compiler:129:in `block in <top (required)>'
  compiler:102:in `each'
  compiler:102:in `<top (required)>'
```

And these errors:

```
bundle exec compiler --product products/dns -v "ga" -e terraform -o "$GOPATH/src/github.com/terraform-providers/terraform-provider-google"
I, [2019-05-06T21:24:54.913649 #62363]  INFO -- : Compiling 'products/dns' (at ga) output to '/Users/KevinMLloyd/Development/go/src/github.com/terraform-providers/terraform-provider-google'
I, [2019-05-06T21:24:54.913889 #62363]  INFO -- : Generating types: ALL
bundler: failed to load command: compiler (compiler)
TypeError: no implicit conversion of Hash into Integer
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:860:in `block in result'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:862:in `result'
  /Users/kevinmlloyd/Development/tooling/google/magic-modules/compile/core.rb:148:in `compile'
  /Users/kevinmlloyd/Development/tooling/google/magic-modules/provider/config.rb:51:in `parse'
  compiler:129:in `block in <top (required)>'
  compiler:102:in `each'
  compiler:102:in `<top (required)>'
```

**Comment by rileykarson** [comment]
Hey @mxplusb!

It looks like you're using a Ruby version of `2.3.0`. MM is generally developed with Ruby `2.6.0` per https://github.com/GoogleCloudPlatform/magic-modules#requirements, though it may work with `2.5.X` still as well.

Does this still occur on `2.6.0` or newer? I'd suspect some functionality change since Ruby `2.3.0` is the root cause here.

**Comment by mxplusb** [comment]
Ah...thanks for pointing that out. I had installed `rbenv` and run `rbenv install 2.6.0`, but forgot to set it. Setting ruby to `2.6.0` fixed it, thanks!
