### ISSUE TITLE
on codelab step 10, failure on compiling template tf.erb

### ISSUE THREAD

**Issue by sebglon** [GoogleCloudPlatform/magic-modules#3220]
I have copied the file on step 9.

```
Error compiling file: templates/terraform/examples/redis_instance_basic.tf.erb
Error compiling file: templates/terraform/resource.html.markdown.erb
bundler: failed to load command: compiler (compiler)
Errno::ENOENT: No such file or directory @ rb_sysopen - templates/terraform/examples/redis_instance_basic.tf.erb
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/compile/core.rb:154:in `read'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/compile/core.rb:154:in `compile_file'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/terraform/examples.rb:115:in `config_documentation'
  (erb):77:in `block in provider_binding'
  (erb):66:in `each'
  (erb):66:in `provider_binding'
  /home/sebastien/.rbenv/versions/2.6.0/lib/ruby/2.6.0/erb.rb:901:in `eval'
  /home/sebastien/.rbenv/versions/2.6.0/lib/ruby/2.6.0/erb.rb:901:in `result'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/compile/core.rb:219:in `compile_string'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/compile/core.rb:154:in `compile_file'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/file_template.rb:64:in `block in generate'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/file_template.rb:64:in `open'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/file_template.rb:64:in `generate'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/terraform.rb:175:in `generate_documentation'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/terraform.rb:163:in `generate_resource'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/core.rb:221:in `generate_object'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/core.rb:212:in `block in generate_objects'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/core.rb:195:in `each'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/core.rb:195:in `generate_objects'
  /home/sebastien/go/src/github.com/GoogleCloudPlatform/magic-modules/provider/core.rb:80:in `generate'
  compiler:218:in `block in <top (required)>'
  compiler:133:in `each'
  compiler:133:in `<top (required)>'

```

**Comment by rileykarson** [comment]
Whoops- this repo's issues don't get monitored much, I just saw this.

Have you created the example file for redis at the end of step 7? The error message indicates that it's looking for that. https://codelabs.developers.google.com/codelabs/magic-modules/index.html#6
